### ISSUE TITLE
Login (Page 1)

### ISSUE THREAD

**Issue by AnkePfei2fer** [AnkePfei2fer/steinchen#2]
## Description
As a user, 
I want to generate a new account or access my existing account 
in order to view my collections.

## Tasks
- [x] text input and submit button 
- [ ] name should have at least 3 letters (display error message, if not)
- [ ] numbers and singel empty spaces are accepted
- [ ] special characters are not accepted
- [x] if name is know show welcome page
- [x] if name is unknown, generate account and display welcome message accordingly

## Screenshot
![image](https://user-images.githubusercontent.com/91462624/143023462-b1036eaa-5231-43e5-a9ec-f63a23f44a14.png)
