### ISSUE TITLE
Welcome (Page 1)

### ISSUE THREAD

**Issue by AnkePfei2fer** [AnkePfei2fer/steinchen#3]
## Description
As a user, 
I want to choose 
whether to view my set or brick collection or to get new building ideas.
Alternatively I want to skip and directly search the LEGO catalog. 

## Tasks
- [x] Welcome new or known user 
- [x] route to set or bricks page via buttons
- [x] route to search 
- [x] route to ideas
- [x] logout function

## Screenshot
![image](https://user-images.githubusercontent.com/91462624/143040266-0189355e-4c56-43f0-af49-836d5f813442.png)
