### ISSUE TITLE
Sets (Page 2)

### ISSUE THREAD

**Issue by AnkePfei2fer** [AnkePfei2fer/steinchen#5]
## Description
As a user,
I want to view my collection of sets or add a new set.

## Tasks
- [x] display sets added by the user as cards including title, picture, number of parts and theme
- [x] sets are ordered alphabetically
- [x] route to access the search to add new sets
- [x] route back to Welcome Page

### bonus features
- [ ] sets can be filtered by theme

## Screenshot
![image](https://user-images.githubusercontent.com/91462624/143026067-aca7a097-6731-4635-8e5f-ef31313a5445.png)
