### ISSUE TITLE
Details (Page 3)

### ISSUE THREAD

**Issue by AnkePfei2fer** [AnkePfei2fer/steinchen#6]
## Description
As a user,
I want to view details of a specific set and download the construction manual.

## Tasks
- [x] display title, picture, set number, theme, number of parts and year of release
- [x] delete set from collection
- [x] route back to sets page

### bonus features 
- [ ] display part list of selected set

## Screenshot
![image](https://user-images.githubusercontent.com/91462624/143030526-65cfa7f2-bda9-466d-81b6-67cff7575c4e.png)
