### ISSUE TITLE
Search (Page 4)

### ISSUE THREAD

**Issue by AnkePfei2fer** [AnkePfei2fer/steinchen#7]
## Description
As a user,
I want to search the catalog
in order to find sets I want to add to my collection.

## Tasks
- [x] text input and submit button to search for set number
- [ ] text input and submit button to search for set name
- [x] if no results were found display error
- [x] display search results according to sets page
- [x] add button in every set card for adding the set to the collection
- [x] route back to Welcome page

### bonus features
- [ ] one single search for set number, set name or theme

## Screenshot
![image](https://user-images.githubusercontent.com/91462624/143030608-057fc273-1491-4ab9-ad7a-cb8f58b7e947.png)
